[package]
name = "doing-rs"
version = "0.1.0"
edition = "2021"
authors = ["Joseph Cooper"]
license = "MIT"


[dependencies]
chrono = { version = "0.4.26", default-features = false, features = ["std", "clock"] }
nom = "7.1.3"

[dev-dependencies]
proptest = "1.2.0"
testresult = "0.3.0"
